# Generated by Django 6.0.7 on 2026-07-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_role_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='password_number',
            new_name='passport_number',
        ),
    ]
