# Generated by Django 6.0.7 on 2026-07-24 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.airline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.airplane'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
