# Generated by Django 6.0.7 on 2026-07-24 09:33

from django.db import migrations

INITIAL_COUNTRIES = [
    {'title': 'Albania', 'code': 'AL'},
    {'title': 'Australia', 'code': 'AU'},
    {'title': 'Austria', 'code': 'AT'},
    {'title': 'Bosnia and Herzegovina', 'code': 'BA'},
    {'title': 'Botswana', 'code': 'BW'},
    {'title': 'Brazil', 'code': 'BR'},
    {'title': 'Bulgaria', 'code': 'BG'},
    {'title': 'Canada', 'code': 'CA'},
    {'title': 'China', 'code': 'CN'},
    {'title': 'Czech Republic', 'code': 'CZ'},
    {'title': 'Denmark', 'code': 'DK'},
    {'title': 'Egypt', 'code': 'EG'},
    {'title': 'Estonia', 'code': 'EE'},
    {'title': 'Finland', 'code': 'FI'},
    {'title': 'France', 'code': 'FR'},
    {'title': 'Georgia', 'code': 'GE'},
    {'title': 'Germany', 'code': 'DE'},
    {'title': 'Greece', 'code': 'GR'},
    {'title': 'Hungary', 'code': 'HU'},
    {'title': 'Iceland', 'code': 'IS'},
    {'title': 'India', 'code': 'IN'},
    {'title': 'Indonesia', 'code': 'ID'},
    {'title': 'Ireland', 'code': 'IE'},
    {'title': 'Israel', 'code': 'IL'},
    {'title': 'Italy', 'code': 'IT'},
    {'title': 'Japan', 'code': 'JP'},
    {'title': 'Latvia', 'code': 'LV'},
    {'title': 'Luxembourg', 'code': 'LU'},
    {'title': 'Mexico', 'code': 'MX'},
    {'title': 'Moldova', 'code': 'MD'},
    {'title': 'Montenegro', 'code': 'ME'},
    {'title': 'Morocco', 'code': 'MA'},
    {'title': 'Netherlands', 'code': 'NL'},
    {'title': 'New Zealand', 'code': 'NZ'},
    {'title': 'Norway', 'code': 'NO'},
    {'title': 'Poland', 'code': 'PL'},
    {'title': 'Portugal', 'code': 'PT'},
    {'title': 'Romania', 'code': 'RO'},
    {'title': 'Spain', 'code': 'ES'},
    {'title': 'Sweden', 'code': 'SE'},
    {'title': 'Switzerland', 'code': 'CH'},
    {'title': 'Thailand', 'code': 'TH'},
    {'title': 'Turkey', 'code': 'TR'},
    {'title': 'Ukraine', 'code': 'UA'},
    {'title': 'United Arab Emirates', 'code': 'AE'},
    {'title': 'United Kingdom', 'code': 'GB'},
    {'title': 'United States', 'code': 'US'},
]


def populate_country(apps, schema_editor):
    Country = apps.get_model('flights', 'Country')
    countries_to_create = [
        Country(code=item['code'], title=item['title'])
        for item in INITIAL_COUNTRIES
    ]
    Country.objects.bulk_create(countries_to_create, ignore_conflicts=True)


def reverse_country(apps, schema_editor):
    Country = apps.get_model('flights', 'Country')
    codes = [item['code'] for item in INITIAL_COUNTRIES]
    Country.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_airline_flight_airplane_alter_airport_name_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_country, reverse_code=reverse_country),
    ]