# Generated by Django 6.0.7 on 2026-07-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20260724_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='airport',
        ),
        migrations.AddField(
            model_name='airline',
            name='airport',
            field=models.ManyToManyField(related_name='airlines', to='flights.airport'),
        ),
    ]
