# Generated by Django 6.0.7 on 2026-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_remove_airline_airport_airline_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('delayed', 'Delayed '), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
