# Generated by Django 6.0.7 on 2026-07-27 22:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_flight_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
