# Generated by Django 6.0.7 on 2026-07-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('cancelled', 'Cancelled'), ('used', 'Used'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
