# Generated by Django 6.0.7 on 2026-08-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
