# Generated by Django 6.0.7 on 2026-08-20 14:16

import tickets.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticket_unique_seat_per_flights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=tickets.storages.TicketStorage(), upload_to=''),
        ),
    ]
